//
// Author: Eitan H.
//

#ifndef ASSEMBLER_SENTENCE_TYPE_H
#define ASSEMBLER_SENTENCE_TYPE_H

typedef enum {
    DEFINE_SENTENCE,
    DIRECTIVE_SENTENCE,
    INSTRUCTION_SENTENCE
} SENTENCE_TYPE;

#endif //ASSEMBLER_SENTENCE_TYPE_H
